import { Component, OnInit } from '@angular/core';
import { FormGroup, FormControl } from '@angular/forms';
import { Store } from '@ngrx/store';
import { AppState } from './store/reducers';
import { setName } from './store/actions/name/name.actions';
import { selectName } from './store/selectors/name/name.selectors';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { selectAlertState } from './store/selectors/alert/alert.selectors';
import { setAlert } from './store/actions/alert/alert.actions';
import { selectPanelState } from './store/selectors/panel/panel.selectors';
import { setPanel } from './store/actions/panel/panel.actions';


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  nameForm = new FormGroup({
    firstName: new FormControl(''),
    lastName: new FormControl(''),
  });
  name$: Observable<string>;
  alert$: Observable<any>;
  panel$: Observable<any>;
  isDrawerOpen = false;

  constructor(private store: Store<AppState>) {
    this.name$ = this.store.select(selectName).pipe(map(name => `Set Name: ${name.firstName} ${name.lastName}`));
    this.alert$ = this.store.select(selectAlertState);
    this.panel$ = this.store.select(selectPanelState);
  }

  submitForm() {
    this.store.dispatch(setName(this.nameForm.value));
  }

  showAlert() {
    this.store.dispatch(setAlert({ title: 'Wrapper Alert', message: 'This alert was generated by the wrapper MFE' }));
  }

  showPanel() {
    this.store.dispatch(setPanel({ title: 'Wrapper Panel', message: 'This panel was generated by the wrapper MFE', components: ['homepage-widget', 'card'] }));
  }

  toggleDrawer() {
    this.isDrawerOpen = !this.isDrawerOpen;
  }
}
